# Generated by Django 4.1.3 on 2023-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="password",
            field=models.CharField(
                default="begugla123", max_length=100, verbose_name="Код"
            ),
        ),
    ]
