# Generated by Django 4.1.3 on 2023-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_contacts_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="password",
            field=models.CharField(default="000", max_length=100, verbose_name="Код"),
        ),
    ]
