# Generated by Django 4.1.3 on 2023-05-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_contacts_options_contacts_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="description",
            field=models.TextField(max_length=100, verbose_name="Краткое описание"),
        ),
    ]
